### ISSUE TITLE
cant go back (seen ?)

### ISSUE THREAD

**Issue by leftysarl** [ramonszo/zuck.js#125]
Hello,

Another issue, i've managed to resolved conflict on the previous issue where we cant go next story x navigation dont work correctly.
Now i'm facing another issue, i cant go back on the stories, here's the generated code:

`      var stories = new Zuck('stories', {
        backNative: false,
        previousTap: false,
        skin: currentSkin['name'],
        autoFullScreen: currentSkin['params']['autoFullScreen'],
        avatars: currentSkin['params']['avatars'],
        paginationArrows: true,
        list: currentSkin['params']['list'],
        cubeEffect: false,
        localStorage: false,
        seen: false,`

If i click going back on the navigation, that paused the video but dont go previous video.
How can we manage to fix that ?

**Comment by etekinbas** [comment]
+++

**Comment by HayotbekAbdulazizov** [comment]
++

**Comment by ramonszo** [comment]
`previousTap` should be `true`
