### ISSUE TITLE
Video don't restart after going back and forward

### ISSUE THREAD

**Issue by lbenedette** [ramonszo/zuck.js#126]
Testing zuck.js in my project I found a problem I think may be a bug, when a video starts and a go back to the past stories and click to go forward again the video start to play when stopped. I think the correct behavior is to start the video from the beginning.

I tested on https://ramon82.com/demo/zuck.js/index.html and the same problems happens, this is a know problem? There's some way to fix it?

**Comment by HayotbekAbdulazizov** [comment]
yes sure is it possible to fix it ?
please help
