### ISSUE TITLE
How to count story view

### ISSUE THREAD

**Issue by amitgarg2002** [ramonszo/zuck.js#145]
i use this library in Laravel project and i am unable to count a view. i try to use callbacks and onEndItem and but its not working. Also console.log not working in this library  . how to count story view

**Comment by ChathuraGH** [comment]
Did you get it to work?

**Comment by ramonszo** [comment]
correct option is `onNextItem` and `onNavigateItem` - not `onEndItem`

**Comment by amitgarg2002** [comment]
@ramonszo what if user have only one story then how we use onNextItem and onNavigateItem to count views.
