### ISSUE TITLE
Multiple instances in one page. 

### ISSUE THREAD

**Issue by ChathuraGH** [ramonszo/zuck.js#148]
Normally you can't use 2+ zuck.js instance in one page, because zuck.js use same id to get model div.
This can be fixed by following. 
1) give "zuck_model_perfix" in options
2) use this prefix to make unique ids
3) use only html classes to style elements in css
😜👈👌😉

**Comment by franklin-hub** [comment]
Hallow please how do i add the perfix in options?

**Comment by franklin-hub** [comment]
> Normally you can't use 2 zuck.js instance in one page, because zuck.js use same id to get model div. This can be fixed by following.
> 
> 1. give "zuck_model_perfix" in options
> 2. use this prefix to make unique ids
> 3. use only html classes to style elements in css
>    😜👈👌😉

Hallow please how do i add the perfix in options?

**Comment by ChathuraGH** [comment]
I have modified the original library and it works. If you, anyone need, I can upload it.👍.

**Comment by ramonszo** [comment]
@ChathuraGH would you mind to create a pull request?

**Comment by ChathuraGH** [comment]
Ok @ramonszo . I will create a pull request 👍.

**Comment by ChathuraGH** [comment]
@ramonszo I created a pull request 😊. I am new to pull requests. So if there is any inconvenience, help me.💪.

**Comment by ChathuraGH** [comment]
What is going on @ramonszo .. 👀👀 I created the pull request. If you can marge it or why it is not been? 🙏🙏.

**Comment by ChathuraGH** [comment]
> Hallow please how do i add the perfix in options?

Did you get it to work?

**Comment by ChathuraGH** [comment]
@ramonszo, what is the problem here friend?

**Comment by ChathuraGH** [comment]
**Hello**  👈👈?

**Comment by ramonszo** [comment]
Hey @ChathuraGH I made a comment on your PR, thanks for the contribution
