### ISSUE TITLE
How to use a normal YYYY-MM-DD HH:MM:SS for "time" property

### ISSUE THREAD

**Issue by Mashiane** [ramonszo/zuck.js#150]
Hi

How does one pass a normal dateTime string as time attribute?

Thanks

**Comment by Mashiane** [comment]
Sorted, just use javascript date object / 1000

**Comment by ramonszo** [comment]
you should use custom templates option: https://github.com/ramonszo/zuck.js/blob/4479a2d585cb837cdc998daf3619b8055518e50b/src/options.ts#L56
