### ISSUE TITLE
Preview issue

### ISSUE THREAD

**Issue by Garyfinder** [ramonszo/zuck.js#161]
I wanted to bring to your attention an issue that we've encountered with the image loading sequence in our parent-child image viewer feature.

Currently, when a user clicks on a parent image and scrolls through the child images, after finishing and reopening the image viewer, the initial image displayed is the last one viewed, rather than starting from the first image.

This loading sequence is not consistent with the expected behavior and may lead to confusion among our users.

Therefore, I kindly request your assistance in addressing this issue quickly.

Could you please investigate the root cause of this problem and implement a solution to ensure that when users reopen the image viewer, it starts from the first image in the sequence?

**Comment by ramonszo** [comment]
this behavior is intentional. no plans to change
