### ISSUE TITLE
Html version not working

### ISSUE THREAD

**Issue by grobitto** [ramonszo/zuck.js#80]
looks like parseItems() call is missing somewhere

**Comment by aydcry** [comment]
I am also working on it and I couldn't make it ; here codepen , pls help ;

https://codepen.io/ayd-in/pen/PomBxzN

**Comment by mariakhn** [comment]
> I am also working on it and I couldn't make it ; here codepen , pls help ;
> 
> https://codepen.io/ayd-in/pen/PomBxzN

> looks like parseItems() call is missing somewhere

HTML version is not working for me too. Is this still an issue?
Any working example of Initialize Zuck via HTML, please? I would greatly appreciate response.
